### ISSUE TITLE
async_setup_platforms issue

### ISSUE THREAD

**Issue by dipseth** [michaelkkehoe/haswidget2#1]
After the most recent HA update this integration was not working for me.  Seems like this method has been deprecated.

After factory resetting my outlets, and reloading the integration a couple times, I was able to fix by changing line [92](https://github.com/michaelkkehoe/haswidget2/blob/d6f8b0d6ec02e4427a8d0f2c40b68fbd36958ad9/custom_components/swidget/__init__.py#L92) in init file to the following:

```
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
```

**Comment by vez727** [comment]
THANK YOU!  Worked perfectly.

**Comment by michaelkkehoe** [comment]
Thank you for the fix!
